# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Backend
  displayName: Backend Build & Push
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          docker build -t teste-back .
          docker tag teste-back bessadocker.azurecr.io/teste-back
          docker push bessadocker.azurecr.io/teste-back