# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Backend
  displayName: Backend Build & Push
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Bemol DEV (12addb71-4126-4486-8c46-12a71769c2ff)'
        azureContainerRegistry: '{"loginServer":"bessadocker.azurecr.io", "id" : "/subscriptions/12addb71-4126-4486-8c46-12a71769c2ff/resourceGroups/RGBessa/providers/Microsoft.ContainerRegistry/registries/bessadocker"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'
        includeLatestTag: true